# Generated by Django 6.0.1 on 2026-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_ban_until_profile_is_banned_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
    ]
