# Generated by Django 6.0.1 on 2026-04-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_average_rating_profile_trust_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trust_score',
        ),
    ]
