# Generated by Django 6.0.1 on 2026-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_image_postimage_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('sports', 'Sports'), ('everyday', 'Everyday'), ('decorations', 'Decorations'), ('misc', 'Miscellaneous')], default='misc', max_length=20),
        ),
    ]
