# Generated by Django 6.0.1 on 2026-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('steam', 'Steam Account'), ('epic', 'Epic Games Account'), ('riot', 'Riot Games Account'), ('psn', 'PlayStation Account'), ('xbox', 'Xbox Account'), ('winter_sports', 'Winter Sports'), ('football', 'Football'), ('basketball', 'Basketball'), ('gym', 'Gym / Fitness'), ('men', 'Men Fashion'), ('women', 'Women Fashion'), ('shoes', 'Shoes'), ('phones', 'Phones'), ('laptops', 'Laptops'), ('accessories', 'Tech Accessories'), ('furniture', 'Furniture'), ('decor', 'Decorations')], default='steam', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('home', 'Home'), ('misc', 'Miscellaneous')], default='misc', max_length=30),
        ),
    ]
