# Generated by Django 6.0.1 on 2026-04-21 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_category_alter_post_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('phone_cases', 'Phone Cases'), ('watches', 'Watches'), ('bags', 'Bags'), ('jewelry', 'Jewelry'), ('steam', 'Steam Account'), ('epic', 'Epic Games Account'), ('riot', 'Riot Games Account'), ('psn', 'PlayStation Account'), ('xbox', 'Xbox Account'), ('winter_sports', 'Winter Sports'), ('football', 'Football'), ('basketball', 'Basketball'), ('gym', 'Gym / Fitness'), ('men', 'Men Fashion'), ('women', 'Women Fashion'), ('shoes', 'Shoes'), ('phones', 'Phones'), ('laptops', 'Laptops'), ('tech_accessories', 'Tech Accessories'), ('furniture', 'Furniture'), ('decor', 'Decorations')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
